name: Bot CI/CD

# Este bloque 'permissions' eleva los permisos del GITHUB_TOKEN para hacer push.
permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script del bot
        run: |
          python bot.py

      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          
          # Si no hay cambios, no hacemos commit
          git diff --quiet && git diff --staged --quiet || git commit -m "Bot updates JSON files [skip ci]"
          
          # Autenticación usando el token en la URL para hacer push a main
          git push "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}" HEAD:main
