name: Bot CI/CD

on:
  # Se ejecuta cuando hay un push a la rama 'main'
  push:
    branches:
      - main

  # Se ejecuta en pull requests dirigidos a la rama 'main'
  pull_request:
    branches:
      - main

  # Se ejecuta diariamente a las 16:00 UTC
  schedule:
    - cron: '0 16 * * *'

  # Permite ejecución manual desde la interfaz de GitHub Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script del bot
        run: |
          python bot.py

      - name: Commit y push de los cambios
        run: |
          # Configurar credenciales de Git para el bot
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Agregar cualquier archivo modificado al índice de Git
          git add .
          
          # Verificar si hay cambios. Si los hay, se crea un commit; si no, se omite.
          git diff --quiet && git diff --staged --quiet || git commit -m "Bot updates JSON files [skip ci]"
          
          # Se hace push a la rama 'main'
          git push origin main
